# 作业
只是用python中的list，实现矩阵的乘法

In [22]:
class MatrixMethod(object):
    #constructor
    def __init__(self,):
        pass #creat an instance variable
    
    #instance method
    def Multiply(x, y):
        assert(len(x[0]) == len(y))
 
        rows = len(x) #乘积矩阵的行
        cols = len(y[0])#乘积矩阵的行
        k_temp = len(x[0])
        result = []
        for i in range(rows):
            r=[]
            for j in range(cols):
                value=0
                for k in range(k_temp):
                    value += x[i][k]*y[k][j]
                r.append(value)
            result.append(r)
        return result

In [23]:
a=[[7,8],[3,4],[3,4],[3,4],[3,4]]
b=[[1,1,1,1,1,1,1,1,1],[3,3,3,1,1,1,1,1,1]]
print("a is\n",a)
print("b is\n",b)

a is
 [[7, 8], [3, 4], [3, 4], [3, 4], [3, 4]]
b is
 [[1, 1, 1, 1, 1, 1, 1, 1, 1], [3, 3, 3, 1, 1, 1, 1, 1, 1]]


In [24]:
d = MatrixMethod.Multiply(a,b)
print("d is\n",d)

d is
 [[31, 31, 31, 15, 15, 15, 15, 15, 15], [15, 15, 15, 7, 7, 7, 7, 7, 7], [15, 15, 15, 7, 7, 7, 7, 7, 7], [15, 15, 15, 7, 7, 7, 7, 7, 7], [15, 15, 15, 7, 7, 7, 7, 7, 7]]


In [25]:
import numpy as np
c = np.dot(a,b)
print("c is\n",c)

c is
 [[31 31 31 15 15 15 15 15 15]
 [15 15 15  7  7  7  7  7  7]
 [15 15 15  7  7  7  7  7  7]
 [15 15 15  7  7  7  7  7  7]
 [15 15 15  7  7  7  7  7  7]]


In [26]:
c-d

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])